name: trivy

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/trivy.yml
      - aws_ecs_fargate/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/trivy.yml
      - aws_ecs_fargate/**
  workflow_dispatch:

env:
  WORKING_DIR: aws_ecs_fargate/

permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

# 連続pushした場合、前のジョブをキャンセルする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy:
    if: ${{ !contains(github.event.head_commit.message, '[skip trivy]') }}
    runs-on: "ubuntu-24.04"
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "./"
          hide-progress: false
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "0" # 0の場合、脆弱性が見つかっても終了しない
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          limit-severities-for-sarif: true # falseの場合、全severityのアラートが出力される

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
          #category: results
